"""記号検出器を学習する（Python 側、Ultralytics）。NMS なしの ONNX に出す。

  python tools/train_det.py --data data/train --val data/val --epochs 40 --imgsz 640 \
      --export models/sym_det.onnx

なぜ Ultralytics か: v8 の損失・task-aligned assigner・mosaic と、事前学習済みの yolov8n が
そのまま使える。姉妹リポ（yolo_lpr_cpp）と同じ判断で、C++ 側は自前の推論
（`pure/infer_v8.hpp` 相当）と評価を持つ。**学習も両言語で**という約束は、C++ 側に
自前トレーナを持つことで守る（そちらは別の段）。

数式で姉妹リポと変えたところ（理由つき）:

  * **左右反転をしない**（`fliplr=0.0`）。数式の記号は鏡像対称でない。`(` と `)` が入れ替わり、
    数字も裏返る。反転させると「裏返った 2 も 2」と教えることになる。
  * 上下反転もしない（`flipud=0.0`）。
  * 回転は小さく（`degrees=3`）。紙を撮った写真の傾き程度。大きく回すと上付きと下付きの
    区別が崩れる（**位置関係が意味を持つ**データなので、幾何の増強は慎重にやる）。
  * mosaic は控えめ（0.5）。4 枚を貼り合わせると式のレイアウトとしては嘘になるが、
    検出器の頑健さには効く。終盤は切る（`close_mosaic`）。
  * 色は動かす（`hsv_*`）。学習データは白地の黒字だが、写真は影や色かぶりがある。

エクスポートは**意図的に NMS なし**: C++/WASM の自作ランタイムに NonMaxSuppression 系の
op を入れたくないので、閾値と NMS は 40 行の自前コードでやる（姉妹リポと同じ）。
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def read_classes(path):
    with open(path, encoding="utf-8") as f:
        return [ln.strip() for ln in f if ln.strip()]


def write_data_yaml(path, train_dirs, val_dir, names):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by tools/train_det.py — クラスの並びは classes.txt が正\n")
        f.write("train:\n")
        for d in train_dirs:
            f.write("  - %s\n" % os.path.abspath(os.path.join(d, "images")).replace("\\", "/"))
        f.write("val: %s\n" % os.path.abspath(os.path.join(val_dir, "images")).replace("\\", "/"))
        f.write("nc: %d\n" % len(names))
        f.write("names: [%s]\n" % ", ".join("'%s'" % n for n in names))
    print("wrote %s (%d クラス)" % (path, len(names)))
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", action="append", default=[], help="mathcam dataset の出力（複数可）")
    ap.add_argument("--val", default="")
    ap.add_argument("--weights", default="yolov8n.pt")
    ap.add_argument("--epochs", type=int, default=40)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--batch", type=int, default=32)
    ap.add_argument("--lr", type=float, default=0.002)
    # 実写の写真に寄せる幾何の増強（紙の傾き・机の斜め・手ぶれ）。**画像側の増強は
    # Ultralytics に任せる**（自作の生成器で 2 言語ぶん書くより安く、枠の追随も面倒がない）
    ap.add_argument("--perspective", type=float, default=0.0006)
    ap.add_argument("--degrees", type=float, default=4.0)
    ap.add_argument("--shear", type=float, default=3.0)
    ap.add_argument("--scale", type=float, default=0.5)
    ap.add_argument("--device", default="")
    # **合成の val で best を選ぶと実写で悪くなる**（実測: 40 epoch のモデルは 13 epoch の
    # モデルより実写で明らかに悪い。合成 val は 100% のままなので気付けない）。
    # 途中の重みを残して、**実写の正解表で選ぶ**ために使う。
    ap.add_argument("--save-period", dest="save_period", type=int, default=-1)
    ap.add_argument("--project", default="runs/det")
    ap.add_argument("--name", default="sym")
    ap.add_argument("--yaml", default="scratch/sym_det.yaml")
    ap.add_argument("--export", default="")
    ap.add_argument("--export-only", dest="export_only", default="",
                    help="学習を飛ばしてこの .pt を出す（export だけ失敗したときに、epoch を"
                         "払い直さずに済ませる。姉妹リポで 71 分の学習を無駄にした経験から）")
    a = ap.parse_args()
    if not a.data and not a.export_only:
        raise SystemExit("--data <mathcam dataset のディレクトリ> を渡してください")

    try:
        from ultralytics import YOLO
    except ImportError:
        print("ultralytics が入っていません: pip install ultralytics")
        return 2

    if a.export_only:
        best = a.export_only
    else:
        names = read_classes(os.path.join(a.data[0], "classes.txt"))
        yaml_path = write_data_yaml(a.yaml, a.data, a.val or a.data[-1], names)
        model = YOLO(a.weights)
        kw = {}
        if a.device:
            kw["device"] = a.device
        if a.save_period > 0:
            kw["save_period"] = a.save_period
        model.train(data=yaml_path, epochs=a.epochs, imgsz=a.imgsz, batch=a.batch, lr0=a.lr,
                    project=a.project, name=a.name, exist_ok=True,
                    # 数式は鏡像対称でないので反転は禁止。回転も小さく（位置関係が意味を持つ）
                    fliplr=0.0, flipud=0.0, degrees=a.degrees, shear=a.shear,
                    perspective=a.perspective,
                    scale=a.scale, translate=0.1, mosaic=0.5, close_mosaic=10,
                    hsv_h=0.015, hsv_s=0.5, hsv_v=0.4, **kw)
        # 重みの場所は trainer に聞く。project/name から組み立てると、Ultralytics の設定に
        # runs_dir が入っているときに外れる（姉妹リポがそれで export に失敗している）
        best = str(getattr(model.trainer, "best", "") or
                   os.path.join(a.project, a.name, "weights", "best.pt"))
    print("best weights: %s" % best)

    if a.export:
        m = YOLO(best)
        # NMS なし・動的軸なしで出す（自作ランタイムが扱える範囲に留める）
        out = m.export(format="onnx", imgsz=a.imgsz, opset=12, simplify=True, nms=False,
                       dynamic=False)
        os.makedirs(os.path.dirname(os.path.abspath(a.export)) or ".", exist_ok=True)
        import shutil
        shutil.copyfile(str(out), a.export)
        print("wrote %s (from %s)" % (a.export, out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
